App1/urls.py
from django.urls import path
from App1.views import IndexView,AutorView,create_autorView

urlpatterns = [
    path('', IndexView),
    path('autor/<int:id>', AutorView),
    path("create_autores/",create_autorView)
]

Taller/urls.py
from django.contrib import admin
from django.urls import path, include
from App1.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App1.urls')),
]

App1/models.py
from django.db import models

class Profesion(models.Model):
    nombre=models.CharField(max_length=75,verbose_name="Nombre")

    def __str__(self) -> str:
        return self.nombre

# Create your models here.
class AutorModel(models.Model):
    nombre = models.CharField(max_length=75,verbose_name="Nombre")
    fecha_nacimiento = models.DateField(verbose_name="Fecha de Nacimiento",null=False, blank=False)
    fecha_fallecimiento = models.DateField(verbose_name="Fecha Fallecimiento",null=True, blank=True)
    profesion = models.ManyToManyField(Profesion,verbose_name="Profesión")
    nacionalidad= models.CharField(max_length=75,verbose_name="Nacionalidad")

    class Meta:
        db_table = "Autores"
        verbose_name = "Autor"
        verbose_name_plural = "Autores"

    def __str__(self) -> str:
        return self.nombre

class FraseModel(models.Model):
    autor = models.ForeignKey(AutorModel,on_delete=models.CASCADE)
    cita = models.TextField(verbose_name="Cita",max_length=500)

    class Meta:
        db_table = "Frases"
        verbose_name = "Frase"
        verbose_name_plural = "Frases"

        def __str__(self) -> str:
            return self.cita

App1/forms.py
from django import forms

class CreatenewAutor(forms.Form):
    nombre=forms.CharField(label="Nombre del autor",max_length=75)
    fecha_nacimiento=forms.DateField(label="Fecha de nacimiento")
    fecha_fallecimiento=forms.DateField(label="Fecha de fallecimiento",required=False)
    nacionalidad=forms.CharField(label="Nacionalidad del autor",max_length=75)

App1/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import AutorModel,FraseModel
from .forms import CreatenewAutor

# Create your views here.
def IndexView(request):
    objeto=AutorModel.objects.all().order_by("id")
    return render(request,"index.html",{"autores":objeto})

def AutorView(request,id):
    autor=get_object_or_404(AutorModel,pk=id)
    return render(request,"autor.html",{"autor":autor})

def create_autorView(request):
    if request.method=="GET":
        return render(request,"create_autores.html",{"form":CreatenewAutor})
    else:
        AutorModel.objects.create(nombre=request.POST["nombre"],fecha_nacimiento=request.POST["fecha_nacimiento"],fecha_fallecimiento=request.POST["fecha_fallecimiento"],nacionalidad=request.POST["nacionalidad"])
        return redirect(request.path)

App1/templates/autor.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Autor</title>
</head>
<body>
    <h1>{{autor.nombre}} </h1>
    {% for i in autor.frasemodel_set.all %}

        <ul>
        <li>{{i.cita}}</li>
        </ul>
    {% endfor %}
</body>
</html>

App1/templates/create_autores.html
<h1>Crear un autor</h1>

<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button>
        Save
    </button>
</form>

App1/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Taller</title>
    <link rel="stylesheet" href="{% static 'estilos.css' %}">
</head>
<body>
   <h1>Hola furra c:.</h1> 
   <script src="{% static 'script.js' %}"></script>
   <br>
   <p>Esto es un parrafo, un muuuuuuuuuy largo parrafo</p>
   <hr>
   {% for i in autores %}
    <li><a href="autor/{{i.id}}"> {{i.nombre}} {{i.apellido}}</a></li>
    <ul>
        {% for j in i.profesion.all %}
        <li>{{j.nombre}}</li>
        {% endfor %}
    </ul>
   {% endfor %}
</body>
</html>